-- =============================================================================
-- V2 — Application-owned tables
-- =============================================================================
--
-- Everything in this file belongs to THIS application and is safe to evolve.
-- Naming follows the portal's established standard so the two schemas read as
-- one system:
--
--   INT<NAME>   numeric columns (ids, scores, counts)
--   TXT<NAME>   character columns
--   DATE<NAME>  date / timestamp columns
--
-- Conventions applied throughout:
--   * Surrogate keys are GENERATED BY DEFAULT AS IDENTITY, so an explicit id may
--     still be supplied when migrating data.
--   * Every table carries the same audit columns (datecreated_on, txtcreated_by,
--     dateupdated_on, txtupdated_by), maintained centrally by JPA auditing.
--   * Status flags are varchar(1): 'A' active/open, 'I' inactive, 'C' closed.
--   * Foreign keys are declared with explicit ON DELETE behaviour.
-- =============================================================================

-- ── Roles and permissions ───────────────────────────────────────────────────

CREATE TABLE app_role (
    introle_id     bigint GENERATED BY DEFAULT AS IDENTITY,
    txtrole_code   varchar(45)  NOT NULL,
    txtrole_name   varchar(100) NOT NULL,
    txtdescription varchar(300),
    -- How far the role's permissions reach; drives data scoping.
    txtscope       varchar(30)  NOT NULL,
    intsort_order  integer      NOT NULL DEFAULT 0,
    txtstatus      varchar(1)   NOT NULL DEFAULT 'A',
    datecreated_on timestamptz  NOT NULL DEFAULT now(),
    txtcreated_by  varchar(60),
    dateupdated_on timestamptz,
    txtupdated_by  varchar(60),
    CONSTRAINT pk_app_role PRIMARY KEY (introle_id),
    CONSTRAINT uq_app_role_code UNIQUE (txtrole_code),
    CONSTRAINT ck_app_role_scope CHECK (txtscope IN ('all', 'assigned-locations', 'assigned-batches')),
    CONSTRAINT ck_app_role_status CHECK (txtstatus IN ('A', 'I'))
);

CREATE TABLE app_permission (
    intpermission_id   bigint GENERATED BY DEFAULT AS IDENTITY,
    txtpermission_code varchar(60)  NOT NULL,
    txtlabel           varchar(100) NOT NULL,
    txtdescription     varchar(300),
    intsort_order      integer      NOT NULL DEFAULT 0,
    CONSTRAINT pk_app_permission PRIMARY KEY (intpermission_id),
    CONSTRAINT uq_app_permission_code UNIQUE (txtpermission_code)
);

CREATE TABLE app_role_permission (
    introle_id       bigint NOT NULL,
    intpermission_id bigint NOT NULL,
    CONSTRAINT pk_app_role_permission PRIMARY KEY (introle_id, intpermission_id),
    CONSTRAINT fk_arp_role FOREIGN KEY (introle_id)
        REFERENCES app_role (introle_id) ON DELETE CASCADE,
    CONSTRAINT fk_arp_permission FOREIGN KEY (intpermission_id)
        REFERENCES app_permission (intpermission_id) ON DELETE CASCADE
);

-- ── Users ───────────────────────────────────────────────────────────────────

CREATE TABLE app_user (
    intuser_id     bigint GENERATED BY DEFAULT AS IDENTITY,
    -- The same identity as participant.intemployee_id, so a portal user and a
    -- trainee are the same number. Unique: one account per employee.
    intemployee_id bigint       NOT NULL,
    txtusername    varchar(60)  NOT NULL,
    txtname        varchar(200) NOT NULL,
    txtemail       varchar(200),
    -- NOTE: stored as plain text for now, at the client's explicit request.
    -- See SecurityConfig / PasswordEncoderConfig: swapping in BCrypt is a
    -- configuration change and a re-hash, not a schema change.
    txtpassword    varchar(200) NOT NULL,
    introle_id     bigint       NOT NULL,
    txtstatus      varchar(1)   NOT NULL DEFAULT 'A',
    datelast_login timestamptz,
    datecreated_on timestamptz  NOT NULL DEFAULT now(),
    txtcreated_by  varchar(60),
    dateupdated_on timestamptz,
    txtupdated_by  varchar(60),
    CONSTRAINT pk_app_user PRIMARY KEY (intuser_id),
    CONSTRAINT uq_app_user_employee UNIQUE (intemployee_id),
    CONSTRAINT uq_app_user_username UNIQUE (txtusername),
    CONSTRAINT fk_app_user_role FOREIGN KEY (introle_id) REFERENCES app_role (introle_id),
    CONSTRAINT ck_app_user_status CHECK (txtstatus IN ('A', 'I'))
);

CREATE INDEX ix_app_user_role ON app_user (introle_id);

-- A user's data scope. The organisation ids reference the portal tables, which
-- are owned elsewhere, so they are deliberately not declared as foreign keys.
CREATE TABLE app_user_location (
    intuser_id     bigint     NOT NULL,
    txtlocation_id varchar(4) NOT NULL,
    CONSTRAINT pk_app_user_location PRIMARY KEY (intuser_id, txtlocation_id),
    CONSTRAINT fk_aul_user FOREIGN KEY (intuser_id)
        REFERENCES app_user (intuser_id) ON DELETE CASCADE
);

CREATE TABLE app_user_batch (
    intuser_id  bigint NOT NULL,
    intbatch_id bigint NOT NULL,
    CONSTRAINT pk_app_user_batch PRIMARY KEY (intuser_id, intbatch_id),
    CONSTRAINT fk_aub_user FOREIGN KEY (intuser_id)
        REFERENCES app_user (intuser_id) ON DELETE CASCADE
);

CREATE INDEX ix_app_user_batch_batch ON app_user_batch (intbatch_id);

-- ── Assessment configuration ────────────────────────────────────────────────

CREATE TABLE app_assessment (
    intassessment_id   bigint GENERATED BY DEFAULT AS IDENTITY,
    txtassessment_name varchar(60)  NOT NULL,
    txtdescription     varchar(300),
    -- Highest achievable score; drives score validation and the CEFR lookup.
    intmax_score       integer      NOT NULL DEFAULT 90,
    intsort_order      integer      NOT NULL DEFAULT 0,
    txtstatus          varchar(1)   NOT NULL DEFAULT 'A',
    datecreated_on     timestamptz  NOT NULL DEFAULT now(),
    txtcreated_by      varchar(60),
    dateupdated_on     timestamptz,
    txtupdated_by      varchar(60),
    CONSTRAINT pk_app_assessment PRIMARY KEY (intassessment_id),
    CONSTRAINT uq_app_assessment_name UNIQUE (txtassessment_name),
    CONSTRAINT ck_app_assessment_max_score CHECK (intmax_score > 0),
    CONSTRAINT ck_app_assessment_status CHECK (txtstatus IN ('A', 'I'))
);

-- The score -> CEFR mapping. Ranges may overlap (Versant publishes B2+ as 68-76
-- and C1 as 76-85), so the level awarding a score is the band with the highest
-- intmin_score, exactly as the frontend's cefrFromScore decides it.
CREATE TABLE app_cefr_band (
    intcefr_band_id bigint GENERATED BY DEFAULT AS IDENTITY,
    -- Free text, not an enum: admins may define custom level labels.
    txtcefr_level   varchar(30) NOT NULL,
    intmin_score    integer     NOT NULL,
    intmax_score    integer     NOT NULL,
    -- Id of an entry in the frontend's CEFR_COLORS palette, e.g. 'green'.
    txtcolor_id     varchar(30) NOT NULL,
    intsort_order   integer     NOT NULL DEFAULT 0,
    datecreated_on  timestamptz NOT NULL DEFAULT now(),
    txtcreated_by   varchar(60),
    dateupdated_on  timestamptz,
    txtupdated_by   varchar(60),
    CONSTRAINT pk_app_cefr_band PRIMARY KEY (intcefr_band_id),
    CONSTRAINT uq_app_cefr_band_level UNIQUE (txtcefr_level),
    CONSTRAINT ck_app_cefr_band_range CHECK (intmin_score >= 0 AND intmax_score >= intmin_score)
);

-- ── Results ─────────────────────────────────────────────────────────────────

CREATE TABLE app_assessment_result (
    intresult_id     bigint GENERATED BY DEFAULT AS IDENTITY,
    intemployee_id   bigint      NOT NULL,
    intassessment_id bigint      NOT NULL,
    -- Nullable: a result row is created when the trainee is assigned to the
    -- assessment and the score is filled in later.
    intscore         integer,
    -- The level is stored alongside the score so historical results keep the
    -- level that was awarded at the time, even if the mapping is edited later.
    txtcefr_level    varchar(30),
    txtremarks       varchar(500),
    dateassessed_on  date,
    datecreated_on   timestamptz NOT NULL DEFAULT now(),
    txtcreated_by    varchar(60),
    dateupdated_on   timestamptz,
    txtupdated_by    varchar(60),
    CONSTRAINT pk_app_assessment_result PRIMARY KEY (intresult_id),
    CONSTRAINT uq_app_result_employee_assessment UNIQUE (intemployee_id, intassessment_id),
    CONSTRAINT fk_app_result_assessment FOREIGN KEY (intassessment_id)
        REFERENCES app_assessment (intassessment_id),
    CONSTRAINT ck_app_result_score CHECK (intscore IS NULL OR intscore >= 0)
);

CREATE INDEX ix_app_result_employee ON app_assessment_result (intemployee_id);
CREATE INDEX ix_app_result_assessment ON app_assessment_result (intassessment_id);

-- Every score change is recorded. Assessment results are the portal's system of
-- record, so "who changed this mark, and what was it before" must be answerable.
CREATE TABLE app_assessment_result_audit (
    intaudit_id      bigint GENERATED BY DEFAULT AS IDENTITY,
    -- Nullable and intentionally not a foreign key: the trail must outlive a
    -- deleted result.
    intresult_id     bigint,
    intemployee_id   bigint      NOT NULL,
    intassessment_id bigint      NOT NULL,
    intold_score     integer,
    intnew_score     integer,
    txtold_cefr      varchar(30),
    txtnew_cefr      varchar(30),
    txtaction        varchar(20) NOT NULL,
    txtchanged_by    varchar(60) NOT NULL,
    datechanged_on   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_app_assessment_result_audit PRIMARY KEY (intaudit_id),
    CONSTRAINT ck_app_result_audit_action CHECK (txtaction IN ('INSERT', 'UPDATE', 'DELETE', 'UPLOAD'))
);

CREATE INDEX ix_app_result_audit_employee ON app_assessment_result_audit (intemployee_id);

-- ── LAP / Remedial ──────────────────────────────────────────────────────────

-- One row per track a trainee has been placed on. A trainee's CURRENT track is
-- the single open row; closing a track sets txtstatus = 'C' and keeps the row as
-- history, which is why this is a table of events rather than a status column on
-- the participant.
CREATE TABLE app_lap_remedial (
    intlap_remedial_id bigint GENERATED BY DEFAULT AS IDENTITY,
    intemployee_id     bigint       NOT NULL,
    intassessment_id   bigint,
    txttrack           varchar(20)  NOT NULL,
    txtstatus          varchar(1)   NOT NULL DEFAULT 'A',
    txtremark          varchar(500),
    datestart_date     date         NOT NULL,
    dateclose_date     date,
    datecreated_on     timestamptz  NOT NULL DEFAULT now(),
    txtcreated_by      varchar(60),
    dateupdated_on     timestamptz,
    txtupdated_by      varchar(60),
    CONSTRAINT pk_app_lap_remedial PRIMARY KEY (intlap_remedial_id),
    CONSTRAINT fk_app_lap_assessment FOREIGN KEY (intassessment_id)
        REFERENCES app_assessment (intassessment_id),
    CONSTRAINT ck_app_lap_track CHECK (txttrack IN ('remedial', 'lap')),
    CONSTRAINT ck_app_lap_status CHECK (txtstatus IN ('A', 'C')),
    CONSTRAINT ck_app_lap_dates CHECK (dateclose_date IS NULL OR dateclose_date >= datestart_date)
);

CREATE INDEX ix_app_lap_employee ON app_lap_remedial (intemployee_id);

-- A trainee can be on at most one open track at a time. Enforced by the database
-- rather than only in service code, so concurrent requests cannot double-place
-- someone.
CREATE UNIQUE INDEX uq_app_lap_open_per_employee
    ON app_lap_remedial (intemployee_id) WHERE txtstatus = 'A';
