DROP TABLE IF EXISTS app_lap_remedial CASCADE;

CREATE TABLE app_lap_remedial (
    intlap_remedial_id bigint GENERATED BY DEFAULT AS IDENTITY,
    intemployee_id     bigint       NOT NULL,
    intassessment_id   bigint,
    txttrack           varchar(20)  NOT NULL,
    txtstatus          varchar(1)   NOT NULL DEFAULT 'A',
    txtremark          varchar(500),
    datestart_date     date         NOT NULL,
    dateclose_date     date,
    datecreated_on     timestamptz  NOT NULL DEFAULT now(),
    txtcreated_by      varchar(60),
    dateupdated_on     timestamptz,
    txtupdated_by      varchar(60),
    CONSTRAINT pk_app_lap_remedial PRIMARY KEY (intlap_remedial_id),
    CONSTRAINT fk_app_lap_assessment FOREIGN KEY (intassessment_id)
        REFERENCES app_assessment (intassessment_id),
    CONSTRAINT ck_app_lap_track CHECK (txttrack IN ('remedial', 'lap')),
    CONSTRAINT ck_app_lap_status CHECK (txtstatus IN ('A', 'C')),
    CONSTRAINT ck_app_lap_dates CHECK (dateclose_date IS NULL OR dateclose_date >= datestart_date)
);

CREATE INDEX ix_app_lap_employee ON app_lap_remedial (intemployee_id);

CREATE UNIQUE INDEX uq_app_lap_open_per_employee
    ON app_lap_remedial (intemployee_id) WHERE txtstatus = 'A';
